### ISSUE TITLE
how to import

### ISSUE THREAD

**Issue by larsrgit** [katspaugh/wavesurfer.ts#22]
Hi,

first of all, I am a beginner when it comes to frontend development, so my question could easily be explained by my lack of knowledge.

I'm trying to import the current alpha in an angular app, after "npm i --save wavesurfer.js@alpha"

`import WaveSurfer from "wavesurfer.js/dist/wavesurfer";`

but get the following error: 

`Error: Module not found: Error: Package path ./dist/wavesurfer is not exported from package </path/to/>node_modules/wavesurfer.js (see exports field in </path/to/>node_modules/wavesurfer.js/package.json)
`

is this a problem on my side or with the current package in combination with angular?

thanks!

**Comment by katspaugh** [comment]
You're almost there! It should be `import WaveSurfer from "wavesurfer.js"`
I'll add this to the readme. 👍

**Comment by larsrgit** [comment]
Thanks, this lead to 
`Could not find a declaration file for module 'wavesurfer.js'. '/path/to/node_modules/wavesurfer.js/dist/wavesurfer.min.js' implicitly has an 'any' type.
`

but i could fix that with 
`npm i --save-dev @types/wavesurfer.js`

this however adds the types from wavesurfer 6.x
I think I already had it that way earlier, but ran into another error when calling WaveSurfer.create(), which sounded like it had something to do with a mismatch of the types to the actual installed package.
But guess I had something else wrong then, since it seems to be working now.

**Comment by katspaugh** [comment]
Oh, I guess I need to export types as well.
I've just published 7.0.0-alpha.26  which should export the types, so you don't need to install the @types package.

**Comment by larsrgit** [comment]
Thanks! Reinstalled, and it works.

**Comment by larsrgit** [comment]
Can you also help me on how to import plugins?
My IDE autocompletes to
`import RegionsPlugin from "wavesurfer.js/dist/plugins/regions";`

but this again throws the error:

`Error: Module not found: Error: Package path ./dist/plugins/regions is not exported from package <path to>/node_modules/wavesurfer.js (see exports field in <path to>/node_modules/wavesurfer.js/package.json)
`

I'm on the current version 7.0.0-alpha.27

**Comment by katspaugh** [comment]
Sorry it didn't work. I've added another export format in 28, could you try again?

**Comment by larsrgit** [comment]
Works fine now. Thanks for the quick fix!

**Comment by katspaugh** [comment]
Good point, @rbracco!

It's a little bit different depending on your environment. E.g. native ES6 modules require an actual URL path including the .js extension. Node and Webpack omit extensions.

I'll add an ES6 import example to the readme.
