### ISSUE TITLE
Use local audio from client

### ISSUE THREAD

**Issue by larsrgit** [katspaugh/wavesurfer.ts#23]
Hi,
another question:

Is it possible to use a local audio file from the client/user?

I already have the audio loaded into a html audio element.
When I now call WaveSurfer.create() and providing the audio element as "media", no wavesurfer Element is visible. When logging the Object into the browser console, the attribute "decodedData" is null.

I also tried directly using the Object URL of the local audio as url in the WaveSurfer.create() call, but this fails due to Angular only allowing property binding when using sanitized object URLs.

Thank you!

**Comment by katspaugh** [comment]
Hey, thanks for the questions, I appreciate you trying out the alpha!
It's indeed possible to use a local audio element like this in this example: https://wavesurfer-ts.pages.dev/tutorial/#/examples/video.js
However, wavesurfer still needs to fetch it in order to decode it. CORS should be enabled if it's a regular URL string.

If you want to avoid fetching the audio twice, you could pas a blob URL like so:
```
        async function loadAudioBlob(url) {
            // Fetch the audio file as a Blob
            const response = await fetch(url);
            const audioBlob = await response.blob();
            return audioBlob;
        }

        async function initAudioElement() {
            // Get the audio element by its ID
            const audioElement = document.getElementById('myAudio');

            // Load the audio file as a Blob
            const audioBlob = await loadAudioBlob('audio/example.mp3');

            // Create an Object URL from the Blob and set it as the audio element's src
            const blobUrl = URL.createObjectURL(audioBlob);
            audioElement.src = blobUrl;

            // You can now use the audio element and blobUrl to init WaveSurfer
            return WaveSurfer.create({
                container: '#container',
                media: audioElement,
                url: blobUrl,
            })
        }

        initAudioElement();
```

**Comment by larsrgit** [comment]
Thank, you. My error was, that I assumed that I have to sanitize the url from my blob. Angular does not allow me to use the url from URL.createObjectURL(audioBlob) for the audio element without sanitizing it. So I assumed this would also be the case for WaveSurfer.
Passing the local html audio with the sanitized URL to WaveSurfer (as media), as well as passing the sanitized URL (as url) did not work. The fix was to just use the blob url without sanitizing.

**Comment by katspaugh** [comment]
Cool! Don't forget to [revoke the URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL) on your component unmount, otherwise it might cause memory leaks.
