### ISSUE TITLE
change options of Plugin after creation

### ISSUE THREAD

**Issue by larsrgit** [katspaugh/wavesurfer.ts#27]
Is it possible to change the options of a plugin after its creation?
The WaveSurfer class has a setOptions function, this would be great for the plugins also.

My use case is an annotator, where the region boundaries are given by a model. They are mostly correct, so per default I want to lock the regions to avoid accidental changes. But I'd like to still allow the user to make the conscious decision to change the region boundaries. For this I would have to be able to change the RegionsPlugin options.

**Comment by katspaugh** [comment]
True, good point about overlapping. I guess we could add both methods.

**Comment by katspaugh** [comment]
I've added `Regions.setOptions` and `Regions.setRegionInteractive(true | false)' which toggles whether a region reacts to any mouse events. Released in alpha-30.

**Comment by larsrgit** [comment]
looks good. Thanks again for the quick responses

**Comment by larsrgit** [comment]
While I dont need this now, it might be good to also add a setOptions function to the to the other plugins.

**Comment by larsrgit** [comment]
Since the Regions API is changed, what is now the intended way to disable and enable resizing, dragging of all existing regions and creation of new regions?

**Comment by larsrgit** [comment]
For existing regions I can loop over all and change the drag and resize parameters.
For adding new regions however, the enableDragSelection function seems not to be working and it would also not allow to disable it again.

**Comment by katspaugh** [comment]
> Since the Regions API is changed, what is now the intended way to disable and enable resizing, dragging of all existing regions and creation of new regions?

Oh, I forgot to keep setOptions and also should've given you a heads up. I'll restore that function.

`enableDragSelection` is a different thing, it allows creating regions by dragging on an empty space on the waveform. Good point about disabling it, I'll add a method for that.

**Comment by katspaugh** [comment]
`enableDragSelection` now returns a callback to disable drag selection.
E.g. `const disableDragSelection = regions.enableDragSelection()`

I've also added a method `setOptions` on individual region objects. It's better to call this method than setting drag and resize directly, because it will also update the region's cursor style.

**Comment by larsrgit** [comment]
Setting options of existing regions works great now, but the drag creation of new regions behaves weird:

1. The color set in the RegionParams passed to enableDragSelection is not used, I can set the color later in a calback for the region-created event, but during dragging no visual feedback is given on the selection.
2. There seems to be a problem with the boundaries of the regions created by drag selection. They can not be changed even if resize is set to true, and when moving the boundary by dragging I get the following error in the console `ERROR TypeError: div.getBoundingClientRect is not a function`

**Comment by katspaugh** [comment]
Gotcha, thank you. Created a new issue for this: https://github.com/katspaugh/wavesurfer.ts/issues/42

**Comment by katspaugh** [comment]
Fixed in alpha.36, thanks for the report @larsrgit!
