### ISSUE TITLE
Scrollbar not hidden

### ISSUE THREAD

**Issue by brollin** [katspaugh/wavesurfer.ts#28]
I've been trying out the alpha since I would like better zooming performance. I'm noticing that I'm seeing a horizontal scrollbar even with the option `hideScrollbar: true`. Incidentally, I also notice it [in the example here](https://wavesurfer-ts.pages.dev/tutorial/#/examples/zoom.js) when the scrollbar checkbox is unchecked:

![image](https://user-images.githubusercontent.com/12655228/232179575-2d4ee40c-661a-4dd3-b946-392328e1594e.png)

**Comment by brollin** [comment]
Interesting, so when I set `fillParent: false`, the scroll bar mostly goes away. Maybe just a matter of documentation in the end.

I should note that the scrollbar mostly goes away, but sometimes when I'm zooming in and out, at some particular zoom levels the canvas (or some child element) seems a little too big, so I get a scroll bar that has very little travel left or right, where the bar is essentially the size of the container.

**Comment by katspaugh** [comment]
Thanks for the bug report!
True, I've noticed this too. There is sometimes a small difference between the container width and the calculated canvas width. I think this is solvable without specifying `fillParent: false`.

**Comment by katspaugh** [comment]
I think the container width overflow and hiding the scrollbar should be fixed now.
In my testing, the only browser where the scrollbar doesn't disappear with the unchecked checkbox is Safari.
Please reopen this issue if you can still reproduce this in alpha-35. Cheers!

**Comment by brollin** [comment]
Thanks just updated to alpha-36 and things are looking good!
