### ISSUE TITLE
minPxPerSec difference between v6 and v7

### ISSUE THREAD

**Issue by brollin** [katspaugh/wavesurfer.ts#29]
In upgrading between v6 and v7, I'm noticing that the pixels per second calculation in v7 seems to be off. Whereas with v6 I was able to synchronize the placement of my own playhead over the waveforms cursor, with everything else unchanged except the upgrade to v7, now I'm seeing the playhead end the built in wavesurfer cursor move at different speeds. This occurs at all zoom levels, and doesn't appear to be a simple shift but some kind of scaling issue. I can provide more information if it's helpful.

**Comment by katspaugh** [comment]
More info would be definitely helpful! It might be a bug in either of the versions :)

**Comment by katspaugh** [comment]
Looks like it was indeed scaled by devicePixelRatio incorrectly. minPxPerSec is the visible pixels, so it shouldn't be.
Could you check if #30 fixes the issue?

**Comment by brollin** [comment]
Thanks for the quick response! Indeed, things are looking good when I pull that change in locally. This is great, the new version now is doing everything I need, and with great types as well 😌 Thanks for all your work on this!

**Comment by katspaugh** [comment]
Awesome, thank you!
