### ISSUE TITLE
audiowaveform pre-decoded peaks + minimap + styles

### ISSUE THREAD

**Issue by SamTyurenkov** [katspaugh/wavesurfer.ts#31]
i had predecoded peaks, they worked well in 6.6.3
![image](https://user-images.githubusercontent.com/19373777/232351781-929d660f-abc3-4774-ac94-da1beedfa6c6.png)

when switching to 7.0.0-alpha they look differently:
![image](https://user-images.githubusercontent.com/19373777/232351790-119c2ddb-16e1-4ef7-b26a-f262b75f4c1c.png)

also note the minimap has scrollbar (it shouldnt). minimap scrollbar appears both with predecoded and default peaks in 7.0.0
![image](https://user-images.githubusercontent.com/19373777/232351909-99b15a57-8c0d-42d8-bd02-c953b6bff9e9.png)

Also how can I style minimap so it is on top of the main waveform, as I had it in 6.6.3? 
I used to apply "absolute/relative position" styles to <wave> elements, but now I can't.

Also didnt manage to apply regions to minimap yet.
-.registerPlugin doesnt work on MinimapPlugin
-defining it in init does nothing as well

**Comment by katspaugh** [comment]
Looks like we'll need to transform the old peaks format. I think v6 had the option to normalize any peak values to the range of -1 to 1, and the new version just expects them to be in this range and doesn't do any transformations.
Could you post a sample of your peaks just to make sure?

**Comment by SamTyurenkov** [comment]
@katspaugh yes, i generated with this library https://github.com/bbc/audiowaveform
the result has values from -127 to +127 it seems. 

as for the frontend normalization - it worked in 6.6.3, but i think it wasnt precise, as many regions were still looking as plane fat wave.

**Comment by katspaugh** [comment]
I see, thank you.
Yeah, I think the v6 normalization function searched for the maximum value in the array, and made that 100% of the waveform height, which didn't always result in a pretty image. I'm not sure how to improve on that. Perhaps passing an explicit range as a parameter along with the peaks?

**Comment by SamTyurenkov** [comment]
@katspaugh actually i think there is nothing can be done with "fatness" of the wave, instead, desktop dj/producer software tend to colorize differently high, mid and low waves, thus waves dont look like this usually.

**Comment by katspaugh** [comment]
Just realized there's an obvious reason for fat waveforms: the current rendering algorithm takes the max peak per sample, whereas it could take e.g. an average.

**Comment by katspaugh** [comment]
I've added peaks normalization in #39 + an option to insert the minimap on top (use `insertPosition: 'beforebegin'`)
