### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled 

### ISSUE THREAD

**Issue by tejaFCProject** [katspaugh/wavesurfer.ts#32]
Hi All, I just tried to updating my existing react project to wavesurfer.ts, I tried to follow the instructions but when I run the app it keeps getting this error
`./node_modules/wavesurfer.js/dist/wavesurfer.js
SyntaxError: /Applications/MAMP/htdocs/lexigo-work/lexigoscribefrontend/node_modules/wavesurfer.js/dist/wavesurfer.js: Support for the experimental syntax 'classProperties' isn't currently enabled (17:12):

  15 | };
  16 | class WaveSurfer extends Player {
> 17 |     options;
     |            ^
  18 |     fetcher;
  19 |     decoder;
  20 |     renderer;

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.`

I wonder if there are anything that are missing??

**Comment by katspaugh** [comment]
Hmm, good question. What output JS version are you targeting in your babel config? Class properties work natively in most browsers, so maybe you could just change the target to ES6.

**Comment by tejaFCProject** [comment]
hi @katspaugh  I use webpack.config actually,

**Comment by katspaugh** [comment]
That's fine, it still uses a babel config in the loader configuration. You might need to tweak the browses it targets. See this for example: https://stackoverflow.com/q/71078039/352796

**Comment by tejaFCProject** [comment]
Let me try and get back to you, thanks

**Comment by tejaFCProject** [comment]
Hi @katspaugh I tried to follow some solution related to bable, the previous error was gone, but now it show me another error as follows:

`./node_modules/wavesurfer.js/dist/plugin/wavesurfer.timeline.min.js 13:20
Module parse failed: Unexpected token (13:20)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         var n = i(139);
|         class r extends n.Z {
>           wavesurfer;
|           container;
|           wrapper;`

any advise?

**Comment by katspaugh** [comment]
Looks like you need to install this: https://babeljs.io/docs/babel-plugin-proposal-class-properties

**Comment by tejaFCProject** [comment]
Hi I already installed that plugin

**Comment by katspaugh** [comment]
Can you post your entire webpack config?

**Comment by tejaFCProject** [comment]
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');

const config = {
    plugins: [
        // Silence mini-css-extract-plugin generating lots of warnings for CSS ordering.
        // We use CSS modules that should not care for the order of CSS imports, so we
        // should be safe to ignore these.
        //
        // See: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250
        new FilterWarningsPlugin({
            exclude: /mini-css-extract-plugin[^]*Conflicting order. Following module has been added:/,
        }),
    ],
    module: {
        rules: [
            {
                test: /\.?js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env', 'react-app'],
                        plugins: [['@babel/plugin-proposal-class-properties', { loose: true }]],
                    },
                },
            },
        ],
    },
};

module.exports = config;

**Comment by tejaFCProject** [comment]
hi @katspaugh thats my webpack.config

**Comment by katspaugh** [comment]
You're using wavesurfer from NPM, right? So it's in `/node_modules/` which is excluded in the Babel config.
You need to tell it to compile it as well:

```
    exclude: {
      and: [/node_modules/], // Exclude libraries in node_modules ...
      not: [
        // Except for a few of them that needs to be transpiled because they use modern syntax
        /wavesurfer\.js/,
      ]
    }
```

Maybe wavesurfer should emit ES2015 instead... I didn't want to go that route initially because the current output works in most browsers.

**Comment by tejaFCProject** [comment]
Hi @katspaugh after I checked it come from timeline.js, is it the right import for timeline ? 

`import TimelinePlugin from 'wavesurfer.js/dist/plugins/timeline';`

**Comment by katspaugh** [comment]
Yes, the import is correct.

**Comment by katspaugh** [comment]
I'm going to adjust our build system, so that the exported modules are in an older, more widely supported version of JavaScript. I'll ping you once it's done.

**Comment by tejaFCProject** [comment]
thanks @katspaugh really appreciated.

**Comment by tejaFCProject** [comment]
Hi @katspaugh bytheway I can run the app now, the above error is gone. But I have one more error on timelineplugin as mentioned bellow

`TypeError: container.appendChild is not a function
    at TimelinePlugin.init (timeline.js:22:1)
    at WaveSurfer.registerPlugin (wavesurfer.js:112:1)
    at wavesurfer.js:107:1
    at Array.forEach (<anonymous>)
    at WaveSurfer.initPlugins (wavesurfer.js:106:1)
    at new WaveSurfer (wavesurfer.js:47:1)
    at Function.create (wavesurfer.js:27:1)
    at Footer.js:285:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)`

**Comment by katspaugh** [comment]
I've just published alpha-33 which emits ES2021 code (no class properties), so you can delete the plugin if you like.

As for the container error, please post your code that initializes the wavesurfer and timeline.

**Comment by katspaugh** [comment]
Oh, I see. It cannot find the timeline container. In fact, it doesn’t accept a selector string like wavesurfer itself, it wants a DOM element. That parameter is optional btw, if you don’t pass any container, it will render itself under the waveform.
I also recommend looking at the [react example](https://wavesurfer-ts.pages.dev/tutorial/#/examples/react.js). It has a useWavesurfer hook that you can copy and paste into your app.

**Comment by katspaugh** [comment]
Also please check the new timeline docs here: https://wavesurfer-ts.pages.dev/docs/types/plugins_timeline.TimelinePluginOptions

**Comment by tejaFCProject** [comment]
Thanks for the support!
