### ISSUE TITLE
wavesurfer events

### ISSUE THREAD

**Issue by stefanomiccoli** [katspaugh/wavesurfer.ts#34]
i find the current list of events emitted by wavesurfer a bit limited for cases where the same instance would be reused for different tracks.

One use case I have in mind is a simple wavesurfer instance with the timeline plugin.

1. User picks a track
2. wavesurfer loads the file
3. once the file is fully loaded, waveform is rendered and `redraw` event is triggered
4. timeline plugin listen to `redraw` and renders its canvases based on the duration (`ws.getDuration()`)
5. user picks another track
6. wavesurfer loads the file and "hides" the current waveform (see `empty()` method of wavesurfer.js). This somehow does not trigger `redraw` and thus the old timeline stays visible
7. once the new file is fully loaded, waveform is rendered and `redraw` event is triggered
8. as timeline plugin is still listening to `redraw` it can now render its canvases based on the new duration (`ws.getDuration()`)

Now, in this specific case it seems to me there's a bug in the drawer that changes duration and width without triggering the `redraw` but I still see the case of an additional event (`init`, `load`, `setSource` or something else more fitting) alongside the existing `loading`, `ready` and `error` events that could make it more explicit the file lifecycle when reusing the same wavesurfer instance with multiple files, both for core plugins and for custom plugins that would need to listen to a single event that means "audio source has changed" rather than workarounds on loading === 0.

**Comment by katspaugh** [comment]
I like the idea! More waveform lifecycle events to reduce wave suffering and maximize wave surfing :)

**Comment by katspaugh** [comment]
FYI, I've added `loading` and `redraw` in alpha-33.

**Comment by katspaugh** [comment]
Yes, we can think of the `loading` as an init event as it’s emitted in the very beginning of loading of an audio file.

Additional logic can be built on top of that in the application code. For example if you want to track the first loading, a flag could be set.

**Comment by stefanomiccoli** [comment]
of course. I think the an init event would be more explicit, but it seems not planned, so i will live with that

**Comment by katspaugh** [comment]
I'm open to an init event, I just don't fully understand when it's supposed to be emitted.
On instantiation? I would suggest running some code right after `WaveSurfer.create`.
On the very first render? `wavesurfer.once('ready')`.

**Comment by stefanomiccoli** [comment]
the `init` event im talking about refers to the file that is passed to the `wavesurfer.load` method. wavesurfer is already initialized, file is about to be downloaded. It's not about the initialization of the wavesurfer instance with `wavesurfer.create`, because i can create a wavesurfer instance without any file, as well as creating an instance with a file, as well as creating an instnace and change the file many times at a later stage.

If wavesurfer didnt allow to load files after the initialization, i think an event that describes the `wavesurfer.create` would suffice as it would both mean that wavesurfer is initialized and a file is selected. Then as a dev I would have to destroy and recreate the wavesurfer instance everytime I want to change the file implicitly re-initializing the plugins.

But since it is possible to load different files later on (think of a playlist if this helps), there's a good case for an event that the describes the `file started to load` or `changed file` scenario, especially when re-initialization of wavesurfer would produce UI glitches with flashing empty space.

Because then, plugins that want to reset themselves as soon as the file changes (contrary to the buggy timeline that keeps showing the duration of the previous file, until the new one is fully downloaded) could listen to the `file-init` event (or anything else), clean up their dom, optionally listening to the loading if they want to show the progress, and finally listening to the `ready` to render again.

It would be more explicit, and the event listeners would not have to set internal flags or implement workarounds to understand which of the `loading` events fired was because the file changed and not because anothe chunk of bytes was downloaded.

Now, regarding the naming, as some events relate to the wavesurfer intance, some to the playback and others to the file, i would have chosen more explicit names as well, for example prefixing every event related to the file with a `file-`, to have `file-init`, `file-loading`, `file-loaded`, `file-error`, but we know hindsight is 20/20...

**Comment by katspaugh** [comment]
I see, it seems like you're describing what the `loading` event does, but you argue it should be called differently.
`loading` indeed sounds more like something that would fire continuously during a file load.
How about a `load-start` event then? I wouldn't use "file" as a prefix because it's not necessarily a file, it can be a URL object from a blob etc.

**Comment by stefanomiccoli** [comment]
ah! i think I finally get where's the misunderstanding. The `loading` i was talking about comes from the stable wavesurfer.js, which docs specify: 
`loading` – Fires continuously when loading using fetch or drag'n'drop. Callback will receive (integer) loading progress in percents [0..100].

while it seems that the new ts one has a different behaviour for that event? wouldnt it be a breaking change?

anyway, you are right, `file-` prefix is not correct as it can be something other than file

**Comment by katspaugh** [comment]
Yes, true, we shouldn't break the old one. With the fetch API it's not trivial to track the loading progress, so I'll probably add `emit('loading', 0)` and `emit('loading', 100)` for backward compatibility, but nothing in between for now.

**Comment by katspaugh** [comment]
I've added a [`load` event](https://github.com/katspaugh/wavesurfer.ts/blob/main/src/wavesurfer.ts#L244) and removed the `loading` event since it's not very useful if we don't track the fetch progress.
