### ISSUE TITLE
Mousedown + Mousemove on minimap with regions

### ISSUE THREAD

**Issue by SamTyurenkov** [katspaugh/wavesurfer.ts#36]
Enable regions on minimap as you suggested in another thread
Then click anywhere on minimap, and with mouse button down start moving the mouse - it creates blacked out regions and errors in console

![image](https://user-images.githubusercontent.com/19373777/232604682-8969a23c-fcd9-432a-944f-ff9c41f6cb93.png)

**Comment by katspaugh** [comment]
Which alpha version are you using? "dragSelection" should not be enabled by default in the latest Regions version (alpha-31).

**Comment by SamTyurenkov** [comment]
@katspaugh just updated to alpha-32, dragSelection is still present by default, but now white color. 
error is gone

**Comment by katspaugh** [comment]
Drag selection cannot be present, it's not enabled unless you call `enableDragSelection`.
Can you reproduce the issue on https://wavesurfer-ts.pages.dev/tutorial/?gist=b508c6acf02223f5ed16cd6a4b17f63e ?
