### ISSUE TITLE
Minimap scroll - feature or bug?

### ISSUE THREAD

**Issue by SamTyurenkov** [katspaugh/wavesurfer.ts#37]
Already mentioned in other topic, but better create a separate. 
Is there a way to fit minimap into the container no matter the sound length? 

Right now I have 3 waves of different length, only the shortest file minimap fits into the container, other minimaps extend it.

**Comment by katspaugh** [comment]
By default both the main waveform and the minimap should fit into the container and not scroll. They only exceed it if you specify a minPxPerSec that results in a longer waveform.

But you probably mean there's a very small scroll which might be a bug?

**Comment by SamTyurenkov** [comment]
@katspaugh no, i mean they dont fit, they even make multiple canvases, only the first canvas fits. 

```
                minimaps[key] = waveSurfers[key].registerPlugin(
                    MinimapPlugin.create({
                        container: document.querySelector('#mix_' + key),
                        scrollParent: true,
                        height: 30,
                        waveColor: '#858585',
                        progressColor: '#f1f1f1',
                        fillParent: true,
                        hideScrollbar: true,
                        minPxPerSec: 2,
                        //peaks: [waves[key].data],
                        plugins: [ regions[key] ], 
                    }),
                );
```

i event specified a small minPxPerSec but nothing changed.

![image](https://user-images.githubusercontent.com/19373777/233500297-c45a64ac-3233-4e26-9e34-482a45ed00b9.png)

**Comment by katspaugh** [comment]
Setting many of those options won't have an effect on the minimap currently. This is how it's initialized inside the plugin:
```
    const data = this.wavesurfer.getDecodedData()
    const media = this.wavesurfer.getMediaElement()

    this.miniWavesurfer = WaveSurfer.create({
      ...this.options,
      container: this.minimapWrapper,
      minPxPerSec: 1,
      fillParent: true,
      media,
      url: media.src,
      peaks: [data.getChannelData(0)],
      duration: data.duration,
    })
```

As you see the container is overwritten (it inserts it into the main wavesurfer container).
Looks like for your application it's required that the minimap accepts a custom container. I'll make an adjustment for that.

**Comment by katspaugh** [comment]
It will now render the minimap into `document.querySelector('#mix_' + key)` as expected.

Please reopen if the issue persists nevertheless.

**Comment by SamTyurenkov** [comment]
@katspaugh 
the issue persists. its not related to container I suppose. 
i installed alpha-38, and its still there:
-multiple canvases are created for minimap and only the first canvas fits the container
