### ISSUE TITLE
Regions - label and time issue

### ISSUE THREAD

**Issue by SamTyurenkov** [katspaugh/wavesurfer.ts#38]
1) in 6.6.3 start/end was specified in min:sec format? if specified just number is it considered minutes or seconds? 
2) in 6.6.3 markers had a property 'label'. if I pass it to region, text doesnt appear, but in your example pages it does: https://wavesurfer-ts.pages.dev/tutorial/#/examples/regions.js

I have it like this
```
                waveSurfers[key].on('decode', function () {
                    for (var i in markers[key]) {
                        regions[key].addRegion({
                            start: markers[key][i]['time'], 
                            end: parseFloat(markers[key][i]['time'])+1, 
                            label: markers[key][i]['label'], 
                            color: markers[key][i]['color']
                        });
                    }
                 }
```

**Comment by katspaugh** [comment]
The timestamps are in seconds. It should be like this:
```
                waveSurfers[key].on('decode', function () {
                    for (var i in markers[key]) {
                        regions[key].addRegion({
                            start: markers[key][i]['time'], // specify only the stat time, the end time will automatically be the same
                            content: markers[key][i]['label'],  // it's called content
                            color: markers[key][i]['color']
                        });
                    }
                 }
```

You can check the docs here: https://wavesurfer-ts.pages.dev/docs/modules/plugins_regions

**Comment by SamTyurenkov** [comment]
@katspaugh nice, i managed to get the labels and position the markers. But whats the correct way to apply styles to them? 
text overlaps. I wanted to make labels hidden by default and make them visible full width when marker is hovered, otherwise it would be messy

only the artist is partially visible, the track name is cut completely
![image](https://user-images.githubusercontent.com/19373777/233499611-1233744e-b897-42fb-98af-ad4b65eec6bb.png)


any custom css property possible?

**Comment by katspaugh** [comment]
`content` can be an HTML element instead of a string. So you can wrap your labels e.g. in a div with a custom class. Use `white-space: nowrap” to fit them on one line.
