### ISSUE TITLE
Add property barHeight to increase bar scale

### ISSUE THREAD

**Issue by zolero** [katspaugh/wavesurfer.ts#44]
Hi @katspaugh,

Thank for making this library, I was wondering, could you add the barHeight property in this package as well. We would like to scale the bars a bit although we can't do that with this library.

Thanks!

**Comment by katspaugh** [comment]
There’s a height option, is that what you want, or you mean stretch the waveform to the full height?

**Comment by katspaugh** [comment]
Turns out the stable wavesurfer version indeed has a `barHeight` version, which is a vertical scaling factor for the waveform. I've added it [here](https://github.com/katspaugh/wavesurfer.ts/commit/b8c788c41063c28b1b9853c95431c5709dccee1e).
Cheers!

**Comment by zolero** [comment]
Awesome! Thanks @katspaugh 🚀
