### ISSUE TITLE
Container content is not rendering with remix.run

### ISSUE THREAD

**Issue by treio** [katspaugh/wavesurfer.ts#47]
Hi there,

I've been trying to implement the latest WaveSurfer Alpha version with Remix.run template and I am unable to figure out where the problem is. It creates WaveSurfer instance and controls via subscriptions working, but the visual part of the container is not rendered. No errors were thrown. 

Here is an example:
https://codesandbox.io/p/sandbox/condescending-dirac-bp7hm0

Any idea what I am doing wrong?

Thanks in advance.

**Comment by treio** [comment]
I just picked one random video from the internet. The sandbox is now updated with a local sample file (much smaller).

**Comment by katspaugh** [comment]
Oh, I got it. It expects an `src` attribute on the media element to fetch and decode the file, and doesn't recognize the `<source>` tag.

You can either change it to `<video src="..." />`, or add an explicit `url` option to the wavesufer config.

Please feel free to submit a PR to support `<source>` tags if you want.

**Comment by katspaugh** [comment]
Also I'm seeing 3 pairs of requests in the network console:
<img width="577" alt="Screenshot 2023-04-25 at 16 19 22" src="https://user-images.githubusercontent.com/381895/234289076-936902f7-2f5a-4ee6-95bd-653a317a21b0.png">

Looks like it re-renders the component 3 times. You might want to memoize some things.

**Comment by treio** [comment]
Ah, I see. 

I can confirm that removing the source tag segment and placing the src prop directly to the media element works well.

I'll investigate further and see if I can memoize the video.

Thank you for the super fast help! 🚀 😎
