### ISSUE TITLE
[iOS] Tapping on the waveform doesn’t work

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.ts#5]
It’s not registering the click.

**Comment by entonbiba** [comment]
@katspaugh how to test this? I think the dist folder is missing from pages.dev site

**Comment by katspaugh** [comment]
It's not missing, it works fine in Chrome and Safari. There's an issue with MIME types in Firefox, so it doesn't work there (there's another issue for that).

**Comment by entonbiba** [comment]
@katspaugh ok I'll have a look locally, just a quick test also found out you can't seek the waveform if it's paused on example for ios.

**Comment by katspaugh** [comment]
@entonbiba you're right, that was exactly the problem.
