### ISSUE TITLE
drawBuffer is not a function  

### ISSUE THREAD

**Issue by tejaFCProject** [katspaugh/wavesurfer.ts#50]
Hi,  I tried to update my project from version 6 to wavesurfer.ts and tried to update the method from this link https://wavesurfer-ts.pages.dev/docs/classes/wavesurfer.WaveSurfer

I tried to implement one function, `wavesurferCursor.drawBuffer();` but it is always returning error `drawBuffer is not a function` I wonder what is the replacement method on the new version?

**Comment by katspaugh** [comment]
Can you describe your use case a little bit?

**Comment by tejaFCProject** [comment]
` useEffect(() => {
        const wavesurferCursor = json(state.wavesurferCursor);
        if (json(state.voiceOver) && props.player) {
            const wavesurferOriginalMusic = json(state.wavesurferOriginalMusic);
            const wavesurferOriginalVoice = json(state.wavesurferOriginalVoice);
            const wavesurferVoiceOver = json(state.wavesurferVoiceOver);
            if (wavesurferCursor && wavesurferOriginalMusic && wavesurferOriginalVoice && wavesurferVoiceOver) {
                wavesurferCursor.options.minPxPerSec = state.waveformZoom;
                wavesurferCursor.drawBuffer();
                wavesurferOriginalMusic.options.minPxPerSec = state.waveformZoom;
                wavesurferOriginalMusic.drawBuffer();
                wavesurferOriginalVoice.options.minPxPerSec = state.waveformZoom;
                wavesurferOriginalVoice.drawBuffer();
                wavesurferVoiceOver.options.minPxPerSec = state.waveformZoom;
                wavesurferVoiceOver.drawBuffer();
                actions.setCenterSecond($footer.current.offsetWidth / 2 / state.waveformZoom);
                actions.setWaveformDuration($footer.current.offsetWidth / state.waveformZoom);
            }
        } else {
            const wavesurferOriginal = json(state.wavesurferOriginal);
            if (wavesurferCursor && wavesurferOriginal) {
                wavesurferCursor.options.minPxPerSec = state.waveformZoom;
                wavesurferCursor.drawBuffer();
                wavesurferOriginal.options.minPxPerSec = state.waveformZoom;
                wavesurferOriginal.drawBuffer();
                actions.setCenterSecond($footer.current.offsetWidth / 2 / state.waveformZoom);
                actions.setWaveformDuration($footer.current.offsetWidth / state.waveformZoom);
            }
        }
    }, [$footer, actions, state.waveformZoom]);`

**Comment by katspaugh** [comment]
You should be using `wavesurfer.setOptions` instead. E.g.:

```
const wavesurferOriginal = json(state.wavesurferOriginal);
if (wavesurferCursor && wavesurferOriginal) {
  wavesurferCursor.setOptions{
    minPxPerSec: state.waveformZoom
  })

  wavesurferOriginal.setOptions({
    minPxPerSec: state.waveformZoom
  })

  actions.setCenterSecond($footer.current.offsetWidth / 2 / state.waveformZoom);
  actions.setWaveformDuration($footer.current.offsetWidth / state.waveformZoom);
}
```

For setting the `minPxPerSec` specifically, there's also a zoom function: `wavesurferOriginal.zoom(state.waveformZoom)`.

Hope this helps!

**Comment by katspaugh** [comment]
Yes, it sets the options and re-draws the waveform.
