### ISSUE TITLE
Sample Rate

### ISSUE THREAD

**Issue by larsrgit** [katspaugh/wavesurfer.ts#52]
Hi, would it be possible to add an option for the sample rate the audio is loaded with? Or does this exist already and i could not find it?

**Comment by katspaugh** [comment]
There’s no such option but you can pass your own AudioContext with your own sample rate.

**Comment by katspaugh** [comment]
There’s no such option but you can pass your own AudioContext with your own sample rate.

**Comment by larsrgit** [comment]
Okay, I think I have it figured out, at least when listening to the audio, the sample rate seems to be higher now.
My code now looks similar to this, is this a correct/good way to achieve this?

`const audio = new Audio()
audio.controls = true
audio.src = this.audioUrl
const audioContext = new AudioContext({sampleRate: 32000})
const mediaElement = audioContext.createMediaElementSource(audio)
mediaElement.connect(audioContext.destination)

const ws = WaveSurfer.create({
  container: document.body,
  media: audio,
})
`

**Comment by katspaugh** [comment]
Wait, sorry, I thought the question was in the v6 forum.

In v7, there’s no pre-defined sample rate other than for rendering. The audio is played via a media element so it uses whatever the native sample rate of the file is. So I’m not sure why you’re hearing a difference.

**Comment by larsrgit** [comment]
Good to know, I was confused by the sample rate of the decoded audio, which I now know is just for rendering.

> So I’m not sure why you’re hearing a difference.

I compared my code with 8kHz and 32kHz (rate of the audio file) to see if it has an effect, but never to not setting the sample rate at all. So I guess my code works, but is not needed when I want the original sample rate.
