### ISSUE TITLE
Minimap doesnt fit container

### ISSUE THREAD

**Issue by SamTyurenkov** [katspaugh/wavesurfer.ts#54]
@katspaugh 
the issue persists. its not related to container I suppose. 
i installed alpha-38, and its still there:
-multiple canvases are created for minimap and only the first canvas fits the container

Originally posted by @SamTyurenkov in https://github.com/katspaugh/wavesurfer.ts/issues/37#issuecomment-1528787006_

**Comment by SamTyurenkov** [comment]
@katspaugh 
so I released a site, you can see the issue live here: https://one-free-dj.pages.dev/

also note, that on mobile minimap can be scrolled with touch, but on desktop you cant scroll it back/further. 
However I would still prefer to have it the size of the container. 

In my case, only the shortest minimap fits the container, two other minimaps with larger duration do not.

**Comment by katspaugh** [comment]
Thanks for sharing!
It should be [fixed](https://github.com/katspaugh/wavesurfer.ts/commit/9aae55ec5aba5bc7f7f868d3d8f6cc054043876a) in alpha-40.
