### ISSUE TITLE
Apply styles to wavesurfer elements

### ISSUE THREAD

**Issue by SamTyurenkov** [katspaugh/wavesurfer.ts#55]
@katspaugh

Actually it doesn't work the way you mentioned, all wavesurfer elements are in shadow-root, and defining .css styles do not affect them. 

Please explain further if I missed something?
I'm going to try something like this: https://stackoverflow.com/questions/47625017/override-styles-in-a-shadow-root-element

---
`content` can be an HTML element instead of a string. So you can wrap your labels e.g. in a div with a custom class. Use `white-space: nowrap` to fit them on one line.

Here's an example:

```
const contentDiv = document.createElement('div')
contentDiv.className = 'wavesurfer-region'
contentDiv.innerText = 'hello'

regions.addRegion({
  start: 1,
  end: 2,
  content: contentDiv
})


// In your CSS
.wavesurfer-region {
  white-space: nowrap;
  display: none;
  width: 100%;
  height: 100%;
}
.wavesurfer-region:hover {
  display: block;
}
```

Originally posted by @katspaugh in https://github.com/katspaugh/wavesurfer.ts/issues/38#issuecomment-1517270902_

**Comment by katspaugh** [comment]
I see. Maybe a shadow root wasn't the best idea. I'll see if I can replace it with something more flexible.

**Comment by SamTyurenkov** [comment]
@katspaugh 

For now managed to add styles like this: 

```
                    var host = document.querySelectorAll('#mix_'+key+' div')[1].querySelectorAll('div')[1];
                    var style = document.createElement( 'style' );
                    style.innerHTML = '.wrapper > div:nth-child(3) > div {pointer-events:none !important} .wavesurfer-region { cursor:initial; pointer-events:all !important; margin-top: 0 !important; opacity: 0; color: white; white-space: nowrap; font-size: 9px; } .wavesurfer-region:hover {opacity:1} .wavesurfer-region span {color: #bebebe;}';
                    host.shadowRoot.appendChild( style );
```

But yeah, feels not very user friendly, also hard to override styles for some divs without any classes.

**Comment by katspaugh** [comment]
To avoid shadow DOM manipulation, you could do the following:

```
  const style = `<style>
    .region {
      white-space: nowrap;
      width: 100%;
      height: 100%;
      opacity: 0;
    }
    .region:hover {
      opacity: 1;
    }
  </style>`

  const div = document.createElement('div')
  div.className = 'region'
  div.innerHTML = 'Yesterday – Beatles' + style

  regions.addRegion({
    start: 2,
    end: 12,
    drag: false,
    resize: false,
    color: 'rgba(0, 0, 100, 0.3)',
    content: div
  })
```

Basically insert the same style block into each content div (or just to the first one, since it will apply globally to the entire shadow container).

**Comment by katspaugh** [comment]
Another alternative would be using JS events instead of `:hover`:

```
  const region = regions.addRegion({
    start: 2,
    end: 12,
    drag: false,
    resize: false,
    color: 'rgba(0, 0, 100, 0.3)',
    content: 'Yesterday – Beatles'
  })

  region.element.opacity = 0

  region.on('over', () => {
    region.element.style.opacity = 1
  })

  region.on('leave', () => {
    region.element.style.opacity = 0
  })
```
