### ISSUE TITLE
dragSelection on minimap regions

### ISSUE THREAD

**Issue by SamTyurenkov** [katspaugh/wavesurfer.ts#56]
@katspaugh

Easily reproduced in your example if you click and hold on the region start/end, not on the body:

![image](https://user-images.githubusercontent.com/19373777/235306541-07b61188-a549-4c60-88c6-1f468b388bbb.png)

---
I think the issue should be fixed now, so I'll close the issue. Please feel free to reopen it if you can reproduce it in the example above. Cheers!

_Originally posted by @katspaugh in https://github.com/katspaugh/wavesurfer.ts/issues/36#issuecomment-1520160455_

**Comment by katspaugh** [comment]
Oh, I see now. It's not dragSelection, it's what I call resizing. Just pass `resize: false` when adding a region. I've updated the example accordingly.

**Comment by SamTyurenkov** [comment]
@katspaugh 

actually I solved by passing drag: false to addRegion method:

```
                        regions[key].addRegion({
                            start: markers[key][i]['time'], 
                            content: contentDiv, 
                            color: markers[key][i]['color'],
                            drag: false
                        });
```
