### ISSUE TITLE
Class name for timeline plugin

### ISSUE THREAD

**Issue by XyzAQWERTY** [katspaugh/wavesurfer.ts#57]
Hi, 

I want to edit the styling of Timeline plugin, so I need a selector for this div
![image](https://user-images.githubusercontent.com/129366472/235418130-c9441854-e637-4e09-9664-e2b7af819542.png)

Thank you

**Comment by katspaugh** [comment]
It accepts a [container option](https://wavesurfer-ts.pages.dev/docs/types/plugins_timeline.TimelinePluginOptions), so you can pass your own div with a custom CSS class.

**Comment by XyzAQWERTY** [comment]
Okay, thanks
