### ISSUE TITLE
Custom Timeline Plugin Class Width and Scrolling

### ISSUE THREAD

**Issue by XyzAQWERTY** [katspaugh/wavesurfer.ts#58]
Hi @katspaugh,

I use my own container for Timeline plugin
![image](https://user-images.githubusercontent.com/129366472/235439915-ef31ef30-f6b6-4431-8acf-ea2333fb4fd4.png)

How to sync the width and scroll with the wavesurfer container?
![image](https://user-images.githubusercontent.com/129366472/235439961-7ca0864e-43f3-4ba2-b068-46fca7203e81.png)

**Comment by katspaugh** [comment]
That's the tricky part. A custom container only works for non-scrolling waveforms. In this regard, your suggestion to have a custom CSS class for the internal container in #57 makes sense. However, the internal container is inside a Shadow DOM node, so applying styles isn't trivial, as explained [here](https://github.com/katspaugh/wavesurfer.ts/issues/55#issuecomment-1528973905).

We could add an option to pass a CSS string like this:

```
const timeline = Timeline.create({
  css: `
   .timeline {
     font-family: Comic Sans;
  }
  .timeline * {
    padding: 2px;
  }
})
```

WDYT?

**Comment by katspaugh** [comment]
Alternatively, it could take an inline style like so:
```
const timeline = Timeline.create({
  style: `font-family: Comic Sans; color: blue;`
})
```

I think this is neater but less flexible.

**Comment by XyzAQWERTY** [comment]
> That's the tricky part. A custom container only works for non-scrolling waveforms. In this regard, your suggestion to have a custom CSS class for the internal container in #57 makes sense. However, the internal container is inside a Shadow DOM node, so applying styles isn't trivial, as explained [here](https://github.com/katspaugh/wavesurfer.ts/issues/55#issuecomment-1528973905).
> 
> We could add an option to pass a CSS string like this:
> 
> ```
> const timeline = Timeline.create({
>   css: `
>     .timeline {
>       font-family: Comic Sans;
>     }
>     .timeline * {
>       padding: 2px;
>     }
>   `
> })
> ```
> 
> WDYT?

I think this approach and the inline style option is good enough

**Comment by XyzAQWERTY** [comment]
Hi @katspaugh,

I still can't use the latest Timeline plugin on version 7.0.0-alpha.41.
It still looks like this:
![image](https://user-images.githubusercontent.com/129366472/235676560-dfbae7eb-28a9-482e-8d34-c564198d7a73.png)

Any suggestion?

**Comment by katspaugh** [comment]
Oh, sorry, I merged it but haven't published yet.

**Comment by katspaugh** [comment]
Published alpha.42.

**Comment by XyzAQWERTY** [comment]
Great! Thank you!
