### ISSUE TITLE
Support for auto scroll and on scroll event

### ISSUE THREAD

**Issue by XyzAQWERTY** [katspaugh/wavesurfer.ts#60]
Hi @katspaugh,

I think it will be good if wavesurfer have auto scroll feature (not auto center), what I mean is when the cursor at the latest point that visible on screen, it scroll the container (so it will not stuck on the middle of the screen).

And the other one is on scroll event, I think if we can get the start time and the end time that visible on the screen it will be good.

Thank you

**Comment by katspaugh** [comment]
> when the cursor at the latest point that visible on screen, it scroll the container (so it will not stuck on the middle of the screen)

You mean it should scroll all the way until the cursor is in the beginning and let it reach the end of the viewport again?

**Comment by XyzAQWERTY** [comment]
> > when the cursor at the latest point that visible on screen, it scroll the container (so it will not stuck on the middle of the screen)
> 
> You mean it should scroll all the way until the cursor is in the beginning and let it reach the end of the viewport again?

Yes, you're right

**Comment by XyzAQWERTY** [comment]
@katspaugh Have you published this new version? Because alpha.42 version is still the latest version
![image](https://user-images.githubusercontent.com/129366472/235885256-f30f15e8-f9d3-4c1d-a744-bccb7a1482c3.png)

**Comment by katspaugh** [comment]
I've just published it now, alpha.43.
