### ISSUE TITLE
Seek on mouse drag

### ISSUE THREAD

**Issue by XyzAQWERTY** [katspaugh/wavesurfer.ts#69]
Hi @katspaugh, 
Can we implement seek on mouse drag? so we can move the seek time like a normal media player

Thank you

**Comment by katspaugh** [comment]
When dragging anywhere on the waveform or dragging the vertical cursor bar?

**Comment by XyzAQWERTY** [comment]
Dragging on the cursor bar, specially in timeline bar
![image](https://github.com/katspaugh/wavesurfer.ts/assets/129366472/896e754c-939d-4406-8672-7a95bf38641f)

**Comment by XyzAQWERTY** [comment]
What I mean is dragging on cursor pointer (marker) or the tip of the cursor, that located on the timeline bar.

**Comment by katspaugh** [comment]
Makes sense, let's do it. 👍
