### ISSUE TITLE
Multitrack plugin issues

### ISSUE THREAD

**Issue by brollin** [katspaugh/wavesurfer.ts#74]
Admittedly, I haven't tried using the multitrack plugin myself yet, but in playing around on the examples page I notice a few issues: 

* When moving the zoom slider, only one track is visually zooming
* I can't change this start time of a track - and don't see the expected console log

(I'm on firefox if that is relevant)

Very excited about this plugin though, hopefully easy fixes.

**Comment by katspaugh** [comment]
Fixed the zoom, thank you! It was a regression in the Envelope plugin.

> I can't change this start time of a track - and don't see the expected console log

How are you changing it? The intended way is by dragging a track with the right mouse button (I would appreciate any insights on the accessibility of this, btw), or by setting the `startPosition` param of the track.

**Comment by brollin** [comment]
Ahh, I didn't know you drag with the right mouse button. I wish I had some useful accessibility insights there. Perhaps it violates the "principle of least surprise" a bit, but it works fine now that I know it. I'll share if I think of something that would feel more natural.
