### ISSUE TITLE
Debouncing on drag to seek

### ISSUE THREAD

**Issue by XyzAQWERTY** [katspaugh/wavesurfer.ts#77]
Hi @katspaugh,
Regarding this feature: https://github.com/katspaugh/wavesurfer.ts/pull/71 
Can we implement debouncing?

So, the call of setTime function not called very often.

**Comment by XyzAQWERTY** [comment]
Or maybe it can accept one more parameter (ex: dragDebounce), if true it will use debouncing, if false it will do as it is

**Comment by katspaugh** [comment]
It felt a little laggy with a denounce when I tried it. Are you running into performance issues?

**Comment by XyzAQWERTY** [comment]
Yes I have performance issue, it feel laggy. I think it because I have onTimeUpdate event listener. Any suggestions?

**Comment by katspaugh** [comment]
We can probably move the cursor on each mousemove but set the time with a debounce. I’ll try this later.

**Comment by XyzAQWERTY** [comment]
The 'seeking' event triggered, but the cursor not moved

**Comment by katspaugh** [comment]
It's quite laggy depending on the network conditions indeed.

**Comment by katspaugh** [comment]
Fixed by #79.

**Comment by XyzAQWERTY** [comment]
Hi @katspaugh,
Have you published the fixed ?

**Comment by katspaugh** [comment]
I've just published alpha.50 👍
