### ISSUE TITLE
Dragging not smooth

### ISSUE THREAD

**Issue by ardiantutomo** [katspaugh/wavesurfer.ts#81]
Hi @katspaugh,

Just want to notify you,
I have late comment in this PR https://github.com/katspaugh/wavesurfer.ts/pull/80

I feel the dragging not smooth enough since this PR.

**Comment by katspaugh** [comment]
I see, thank you! Maybe 1px would be a better threshold. Without it, clicking creates small drags.

**Comment by katspaugh** [comment]
Or even better, we should check the sum of all mousemove deltas against a threshold, instead of each delta which are small individually.

**Comment by ardiantutomo** [comment]
Hi @katspaugh,

Can you published this fixed?

**Comment by katspaugh** [comment]
Published 👍
