### ISSUE TITLE
Click on a region triggers the update event

### ISSUE THREAD

**Issue by Killian-denechere** [katspaugh/wavesurfer.ts#85]
Hello @katspaugh,

First of all, I really want to say I love this tool !

By using this new alpha version recently, I've noticed that clicking on a region triggers the "update-end" event on it (even if the region has not been resized or moved).
I suppose it's not the expected behavior since the "update" event is not triggered too by the same action.

(I'm using alpha 53 version)
Thanks

**Comment by katspaugh** [comment]
Thanks for the report @Killian-denechere! Fixed in #87.

**Comment by katspaugh** [comment]
Awesome, thanks for testing! I'll just merge that PR now. 👍
