### ISSUE TITLE
Timeline cursor not really smooth when drag

### ISSUE THREAD

**Issue by tejaFCProject** [katspaugh/wavesurfer.ts#88]
Hey, please ignore if its not really make sense for you lol :D so the problem is I tried to develop using timeline plugin and I just feel that when I drag the timeline cursor the changes is not that smooth, im not sure if its the right terms to describe the issue, so I wondering if we can make it smoother??

**Comment by katspaugh** [comment]
Makes sense! I've added a debounce, it should make it smoother.

**Comment by matadantelinga** [comment]
is there anything that we should do on our side? or is it just updating the package?

**Comment by katspaugh** [comment]
Yeah, I've just published alpha.57. Please let me know if it's smoother for you now.
