### ISSUE TITLE
Large file loading fails with RangeError: too many function arguments

### ISSUE THREAD

**Issue by TSnake41** [katspaugh/wavesurfer.ts#92]
wavesurfer.ts crashes when trying to load a quite large file (~200 MiB).
(Some other browsers may have a different error, but it is related to the same line, like `RangeError: Maximum call stack size exceeded`)

It looks related to this line
https://github.com/katspaugh/wavesurfer.ts/blob/1e3b9273593c75a7c02846fa75b34a1744e6334c/src/decoder.ts#L16

`t[0]` can be up to ~1 million elements which makes `...t[0]` to cause this error (due to interpreter limits).

**Comment by katspaugh** [comment]
Good catch, thank you!
