### ISSUE TITLE
Beta: Could not find a declaration file TS(7016) error

### ISSUE THREAD

**Issue by jgentes** [katspaugh/wavesurfer.ts#95]
Looks like the types aren't coming through properly with the new beta version. I'm seeing this error:

```
Could not find a declaration file for module 'wavesurfer.js'. '../node_modules/wavesurfer.js/dist/wavesurfer.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/wavesurfer.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'wavesurfer.js';`ts(7016)
```

![image](https://github.com/katspaugh/wavesurfer.ts/assets/1149470/dd34694b-ff91-49f0-a15b-437706f33913)

Version is "7.0.0-beta.1"

Also, I have removed `@types/wavesurfer.js`

**Comment by katspaugh** [comment]
Thanks for the report! Looks like it cannot automatically match the import and its type by name as is the case with ES6 modules. I'm testing a different approach with an explicit types file.

**Comment by katspaugh** [comment]
I've made the ES6 module the main export instead of the min.js file. It should now pick up types automatically. 👍
